echo <<
<JSON
        [
        {
"id": "s10001",
"shop_name": "上沙麦当劳",
"shop_img": "http://www.homework.com/images/shop-logo.png",
"shop_rating": 4.7,
"brand": true,
"on_time": true,
"fengniao": true,
"bao": true,
"piao": true,
"zhun": true,
"start_send": 20,
"send_cost": 5,
"distance": 637,
"estimate_time": 30,
"notice": "新店开张，优惠大酬宾！",
"discount": "新用户有巨额优惠！"
},
{
"id": "s10002",
"shop_name": "正宗川味卤鸡蛋，味道好得很！",
"shop_img": "http://www.homework.com/images/shop-logo.png",
"shop_rating": 3.5,
"brand": false,
"on_time": true,
"fengniao": false,
"bao": true,
"piao": false,
"zhun": true,
"start_send": 20,
"send_cost": 0,
"distance": 347,
"estimate_time": 20,
"notice": "新店开张，优惠大酬宾！",
"discount": "新用户有巨额优惠！"
},
{
"id": "s10003",
"shop_name": "有家蛋糕店（下沙店）",
"shop_img": "http://www.homework.com/images/shop-logo.png",
"shop_rating": 4.4,
"brand": false,
"on_time": true,
"fengniao": false,
"bao": true,
"piao": false,
"zhun": true,
"start_send": 80,
"send_cost": 0,
"distance": 637,
"estimate_time": 30,
"notice": "新店开张，优惠大酬宾！",
"discount": "新用户有巨额优惠！"
},
{
"id": "s10004",
"shop_name": "宇宙炸鸡（上沙店）",
"shop_img": "http://www.homework.com/images/shop-logo.png",
"shop_rating": 4.3,
"brand": true,
"on_time": false,
"fengniao": false,
"bao": true,
"piao": false,
"zhun": true,
"start_send": 20,
"send_cost": 5,
"distance": 127,
"estimate_time": 10,
"notice": "新店开张，优惠大酬宾！",
"discount": "新用户有巨额优惠！"
},
{
"id": "s10005",
"shop_name": "胖哥烧烤（车公庙店）",
"shop_img": "http://www.homework.com/images/shop-logo.png",
"shop_rating": 4.6,
"brand": false,
"on_time": false,
"fengniao": false,
"bao": true,
"piao": false,
"zhun": true,
"start_send": 20,
"send_cost": 4,
"distance": 500,
"estimate_time": 10,
"notice": "新店开张，优惠大酬宾！",
"discount": "新用户有巨额优惠！"
}
]
JSON;